name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
      - name: Run go fmt
        run: go fmt ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Run go test
        run: go test -v ./...
